on:
  pull_request:
  push:
      branches: [main, development]

jobs:
  ci_dev:
    runs-on: ubuntu-latest
    environment: Development
    if: github.ref == 'refs/heads/development'
    steps:
      - uses: actions/checkout@v4
      - name: Test
        run: |
          npm install
          npm test
          REACT_APP_BACKEND=${{ vars.BACKEND_ADDRESS }} npm run build
      - name: Deploy
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          workingDirectory: 'workers/development'
  ci_prod:
    runs-on: ubuntu-latest
    environment: Production
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v4
      - name: Test
        run: |
          npm install
          npm test
          REACT_APP_BACKEND=${{ vars.BACKEND_ADDRESS }} npm run build
      - name: Deploy
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          workingDirectory: 'workers/production'
